---
- name: Configure user groups
  hosts: all
  become: true

  vars:
    username: fdong
    user_groups:
      - audio
      - video
      - storage
      - optical
      - network
      - power
      - input

  tasks:
    - name: Ensure user "{{ username }}" is in required groups
      ansible.builtin.user:
        name: "{{ username }}"
        groups: "{{ user_groups }}"
        append: true
