---
- name: Stow dotfiles
  hosts: localhost
  connection: local

  vars:
    dotfiles_dir: "{{ ansible_env.HOME }}/.dotfiles"
    stow_dirs:
      - foot
      - hyprland
      - keyd
      - kitty
      - matugen
      - neovim
      - swayosd
      - wallpaper
      - waybar
      - wezterm
      - zsh

  tasks:
    - name: Stow each dotfile directory
      ansible.builtin.command:
        cmd: stow --dir={{ dotfiles_dir }} --target={{ ansible_env.HOME }} {{ item }}
      args:
        creates: "{{ ansible_env.HOME }}/.{{ item }}"
      loop: "{{ stow_dirs }}"

    # - name: Get hostname
    #   ansible.builtin.command: hostname
    #   register: current_hostname
    #
    # - name: Delete existing hardware-configuration.nix
    #   ansible.builtin.file:
    #     path: "{{ ansible_env.HOME }}/.nixos-config/hosts/{{ current_hostname.stdout }}/hardware-configuration.nix"
    #     state: absent
    #
    # - name: Copy hardware-configuration.nix to nixos-config host directory
    #   ansible.builtin.copy:
    #     src: /etc/nixos/hardware-configuration.nix
    #     dest: "{{ ansible_env.HOME }}/.nixos-config/hosts/{{ current_hostname.stdout }}/hardware-configuration.nix"
    #     remote_src: true
